-- VERDULERÍA TERÁN — esquema Supabase
-- Ejecuta este SQL en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text not null default 'Verduras',
  unidad text not null default 'kg',
  precio numeric(10,2) not null default 0 check (precio >= 0),
  imagen_url text,
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pedidos (
  id uuid primary key default gen_random_uuid(),
  numero_pedido text unique not null,
  nombre_cliente text not null,
  telefono text not null,
  direccion text not null,
  referencia text,
  forma_pago text not null,
  productos jsonb not null default '[]'::jsonb,
  total numeric(10,2) not null default 0,
  estado text not null default 'Pendiente',
  created_at timestamptz not null default now()
);

create or replace function public.generar_numero_pedido()
returns trigger language plpgsql as $$
begin
  if new.numero_pedido is null or btrim(new.numero_pedido) = '' then
    new.numero_pedido := 'VT-' || lpad(nextval('public.pedido_numero_seq')::text, 6, '0');
  end if;
  return new;
end;
$$;

-- Secuencia separada para los números VT.
create sequence if not exists public.pedido_numero_seq start 1;

create or replace trigger pedidos_numero_before_insert
before insert on public.pedidos
for each row execute function public.generar_numero_pedido();

-- Actualiza updated_at de productos.
create or replace function public.actualizar_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now(); return new;
end;
$$;

drop trigger if exists productos_updated_at on public.productos;
create trigger productos_updated_at before update on public.productos
for each row execute function public.actualizar_updated_at();

-- RLS.
alter table public.productos enable row level security;
alter table public.pedidos enable row level security;

-- El cliente puede ver productos activos.
drop policy if exists productos_public_select on public.productos;
create policy productos_public_select on public.productos
for select using (activo = true);

-- El cliente puede crear pedidos. No se habilita lectura pública de pedidos.
drop policy if exists pedidos_public_insert on public.pedidos;
create policy pedidos_public_insert on public.pedidos
for insert with check (true);

-- Administración: usuarios autenticados pueden administrar productos y pedidos.
-- Si quieres restringirlo a un único administrador, reemplaza estas políticas
-- por una política basada en auth.uid() o en app_metadata.role='admin'.
drop policy if exists productos_authenticated_all on public.productos;
create policy productos_authenticated_all on public.productos
for all to authenticated using (true) with check (true);

drop policy if exists pedidos_authenticated_all on public.pedidos;
create policy pedidos_authenticated_all on public.pedidos
for all to authenticated using (true) with check (true);

-- Productos iniciales de referencia.
insert into public.productos (nombre,categoria,unidad,precio) values
('Tomate','Verduras','kg',4.50),
('Cebolla roja','Verduras','kg',3.80),
('Zanahoria','Verduras','kg',2.50),
('Lechuga','Verduras','unidad',2.00),
('Limón','Frutas','kg',5.00),
('Papa amarilla','Tubérculos','kg',3.50),
('Brócoli','Verduras','kg',5.00),
('Pepino','Verduras','kg',3.20),
('Palta','Frutas','kg',8.50),
('Plátano','Frutas','kg',4.00),
('Manzana','Frutas','kg',6.50),
('Ajo','Verduras','kg',10.00)
on conflict do nothing;
